batch:
  dim_store:
    tables:
      - source_schema : "core"
        source_table : "core.customers"
        sink_table : "fraud_catalog.raw.customers"
        replication_column : "last_modified_at"
        expected_columns: ["customer_id","name","email","phone","dob","kyc_status","registration_date","last_modified_at"]

      - source_schema: "core"
        source_table: "core.users"
        sink_table: "fraud_catalog.raw.users"
        replication_column: "last_modified_at"
        expected_columns: ["user_id","customer_id","name","email","phone","dob","kyc_status","registration_date","last_modified_at" ]

      - source_schema: "core"
        source_table: "core.credit_cards"
        sink_table: "fraud_catalog.raw.credit_cards"
        replication_column: "last_modified_at"
        expected_columns: [ "card_id","credit_card_number","customer_id","status","issued_on","card_type","limit","last_modified_at" ]

      - source_schema: "core"
        source_table: "core.credit_card_user_map"
        sink_table: "fraud_catalog.raw.credit_card_user_map"
        replication_column: "last_modified_at"
        expected_columns: [ "card_id","user_id","role","status","linked_on","last_modified_at" ]

      - source_schema: "core"
        source_table: "core.devices"
        sink_table: "fraud_catalog.raw.devices"
        replication_column: "last_modified_at"
        expected_columns: [ "device_id","user_id","first_seen_at","device_type","os","is_verified","last_modified_at" ]

      - source_schema: "core"
        source_table: "core.merchants"
        sink_table: "fraud_catalog.raw.merchants"
        replication_column: "last_modified_at"
        expected_columns: [ "merchant_id","name","risk_score","last_modified_at" ]

    watermark_table: "core.ingestion_watermarks"

  chargebacks:
    bucket_name: ""
    path: ""

streaming:
  kafka:
    - topic_name: "logins"
      sink_table: "fraud_catalog.raw.login_events"
      sample_event: '{"login_id": "e43ea563-301a-46c5-828e-f4bad610c9df", "user_id": "a50a130f-4346-413e-a58b-3d1230ab8503", "timestamp": "2025-06-08 08:39:49", "ip_address": "223.134.18.72", "device_id": "6ca99a27-36bb-49c3-a295-8bc848f85039", "geo_location": "POINT(-163.670153 -38.4164835)", "session_id": "8f40e0fc-35f7-47e2-a781-f09e1c35c187"}'

    - topic_name: "transactions"
      sink_table: "fraud_catalog.raw.transactions"



